from typing import Any
class NvParam:
    name: str
    layer: int
    value: Any
    default: Any
    type: Any
    getter: Any
    setter: Any
    def __init__(self, name: str, layer: int, value: Any, default: Any, type: Any, getter: Any = ..., setter: Any = ...) -> None: ...
    def check(self, value: Any) -> bool: ...
    def __repr__(self) -> str: ... 
    def reset(self) -> None: ...
    def get(self) -> Any: ...
    def set(self, value: Any) -> None: ...