from nevu_ui.core.enums import CacheName, CacheType

class Cache:
    def clear(self): ...
    def clear_selected(self, blacklist = None, whitelist = None): ...
    def get(self, type: CacheType): ...
    def set(self, type: CacheType, value): ...
    def get_or_set_val(self, type: CacheType, value): ...
    def get_or_exec(self, type: CacheType, func): ...
    def __getattr__(self, type): ...
    def __getitem__(self, key: CacheType): ...
    def copy(self): ...
    def __deepcopy__(self, memo): ...