from typing import Any, Callable, Dict, List, Optional, Union

from nevu_ui.fast.nevucache.nevucache import Cache
from nevu_ui.fast.nvparam.nvparam import NvParam
from nevu_ui.fast.nvrect.nvrect import NvRect
from nevu_ui.fast.nvvector2.nvvector2 import NvVector2

class NevuCobject:
    _sended_z_link: bool
    _dragging: bool
    _is_kup: bool
    _kup_abandoned: bool
    _force_state_set_continue: bool
    _visible: bool
    _active: bool
    _changed: bool
    _first_update: bool
    _wait_mode: bool
    _dead: bool
    booted: bool
    _custom_secondary_update: bool
    _custom_animation_update: bool
    _custom_logic_update: bool
    _custom_event_update: bool
    _custom_primary_draw: bool
    _custom_secondary_draw: bool
    _custom_secondary_draw_content: bool
    _custom_secondary_draw_end: bool
    coordinates: NvVector2
    absolute_coordinates: NvVector2
    size: NvVector2
    _resize_ratio: NvVector2
    _style: Any
    animation_manager: Any
    hover_state: Any
    params: List[NvParam]
    _blacklisted_params: List[Any]
    _next_frame_functions: List[Any]
    _params_map: Dict[str, NvParam]
    _param_links: Dict[Any, Any]
    cache: Cache
    specific_cache_whitelist: List[Any]

    def __init__(self, *args, **kwargs) -> None: ...
    def _get_param_names(self) -> List[str]: ...
    @staticmethod
    def _ensure_func_safety(function) -> Callable | None: ...
    def _find_param(self, name: str) -> NvParam: ...
    def _set_node_type(self, node_type: int) -> None:
        """
        1 - Layout\n
        0 - Widget
        """
        ...
    def _add_param(
        self,
        name: str,
        supported_classes: Any,
        default: Any,
        getter: Any,
        setter: Any,
        layer: int,
    ) -> None: ...
    def get_param_strict(self, name: str) -> NvParam: ...
    def get_param(self, name: str) -> Optional[NvParam]: ...
    def get_param_value(self, name: str) -> Any: ...
    def set_param_value(self, name: str, new_value: Any) -> None: ...
    def relx_custom(self, num: float, min: float, max: float) -> float: ...
    def rely_custom(self, num: float, min: float, max: float) -> float: ...
    def relm_custom(self, num: float, min: float, max: float) -> float: ...
    def relx(self, num: float) -> float: ...
    def rely(self, num: float) -> float: ...
    def relm(self, num: float) -> float: ...
    def rel(self, vec: NvVector2) -> NvVector2: ...
    def get_nvrect(self) -> NvRect: ...
    def set_coordinates(self, coordinates: NvVector2) -> None: ...
    def clear_all(self) -> None: ...
    def clear_surfaces(self) -> None: ...
    def update(self) -> None: ...
    def draw(self) -> None: ...
    def _click(self) -> None: ...
    def _unhover(self) -> None: ...
    def _hover(self) -> None: ...
    def _kup(self) -> None: ...
    def _kup_abandon(self) -> None: ...
    def secondary_update(self) -> None: ...
    def _logic_update(self) -> None: ...
    def _animation_update(self) -> None: ...
    def _event_update(self, events: Any) -> None: ...
    def on_change(self) -> None: ...
    def _on_change_system(self) -> None: ...
    def _primary_draw(self) -> None: ...
    def secondary_draw(self) -> None: ...
    def secondary_draw_content(self) -> None: ...
    def _secondary_draw_end(self) -> None: ...
    def on_state_change(self, value: Any) -> None: ...
    def _on_state_change_system(self, value: Any) -> None: ...
    def after_state_change(self) -> None: ...
    def _after_state_change_system(self) -> None: ...
    def _group_on_click(self) -> None: ...
    def _group_on_keyup(self) -> None: ...
    def _group_on_hover(self) -> None: ...
    def _group_on_keyup_abandon(self) -> None: ...
    def _group_on_unhover(self) -> None: ...
    def _on_click_system(self) -> None: ...
    def _on_keyup_system(self) -> None: ...
    def _on_hover_system(self) -> None: ...
    def _on_keyup_abandon_system(self) -> None: ...
    def _on_unhover_system(self) -> None: ...
    def get_actual_size(self) -> NvVector2: ...
