from typing import Any, Callable, Dict, List, Optional
from nevu_ui.fast.nvvector2.nvvector2 import NvVector2
from nevu_ui.fast.nvparam.nvparam import NvParam
from nevu_ui.fast.nvrect.nvrect import NvRect
from nevu_ui.fast.nevucache.nevucache import Cache
from nevu_ui.fast.zsystem.fast_zsystem import ZRequest
from nevu_ui.core.callbacks import Callbacks

class NevuCobject:
    _sended_z_link: bool
    _dragging: bool
    _is_kup: bool
    _kup_abandoned: bool
    _force_state_set_continue: bool
    _visible: bool
    _active: bool
    _changed: bool
    _first_update: bool
    _wait_mode: bool
    _dead: bool
    booted: bool
    _custom_secondary_update: bool
    _custom_animation_update: bool
    _custom_logic_update: bool
    _custom_event_update: bool
    _custom_secondary_draw: bool
    _custom_secondary_draw_content: bool
    _custom_secondary_draw_end: bool
    _custom_primary_draw: bool
    coordinates: NvVector2
    absolute_coordinates: NvVector2
    size: NvVector2
    _resize_ratio: NvVector2
    _style: Any
    hover_state: Any
    _system_callbacks: Callbacks
    params: List[NvParam]
    _blacklisted_params: List[Any]
    _next_frame_functions: List[Callable[..., Any]]
    node_type: int
    _params_map: Dict[str, NvParam]
    _param_links: Dict[Any, Any]
    cache: Cache
    _has_position_anim: bool
    _z_request: ZRequest
    specific_cache_whitelist: List[Any]

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def _set_node_type(self, node_type: int) -> None: ...
    def _get_param_names(self) -> List[str]: ...
    def _find_param(self, name: str) -> Optional[NvParam]: ...
    def _add_param(
        self,
        name: str,
        supported_classes: Any,
        default: Any,
        getter: Any,
        setter: Any,
        layer: int,
    ) -> None: ...
    def get_param_strict(self, name: str) -> NvParam: ...
    def get_param(self, name: str) -> Optional[NvParam]: ...
    def get_param_value(self, name: str) -> Any: ...
    def set_param_value(self, name: str, new_value: Any) -> None: ...
    def relx_custom(self, num: float, min: float, max: float) -> float: ...
    def rely_custom(self, num: float, min: float, max: float) -> float: ...
    def relm_custom(self, num: float, min: float, max: float) -> float: ...
    def relx(self, num: float) -> float: ...
    def rely(self, num: float) -> float: ...
    def relm(self, num: float) -> float: ...
    def rel(self, vec: NvVector2) -> NvVector2: ...
    def get_nvrect(self) -> NvRect: ...
    def set_coordinates(self, coordinates: NvVector2) -> None: ...
    def clear_all(self) -> None: ...
    def clear_surfaces(self) -> None: ...
    def get_actual_size(self) -> NvVector2: ...
    def _event_cycle(self, type: Any, *args: Any, **kwargs: Any) -> None: ...
    def update(self) -> None: ...
    @staticmethod
    def _ensure_func_safety(function: Optional[Callable[..., Any]]) -> Any: ...
    def draw(self) -> None: ...
    def _run_callbacks(self, bind_type: Any, *args: Any) -> None: ...
    def _click(self) -> None: ...
    def _unhover(self) -> None: ...
    def _hover(self) -> None: ...
    def _kup(self) -> None: ...
    def _kup_abandon(self) -> None: ...
    def set_hover_state(self, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
