from __future__ import annotations

from typing import Any

from nevu_ui.fast.nvvector2.nvvector2 import NvVector2
from nevu_ui.fast.nvparam.nvparam import NvParam
from nevu_ui.animations.animation_manager import AnimationManager
from nevu_ui.fast.nvrect.nvrect import NvRect
class NevuCobject:
    coordinates: NvVector2
    absolute_coordinates: NvVector2
    size: NvVector2
    _resize_ratio: NvVector2

    params: list[NvParam]
    _blacklisted_params: list[str]
    _param_links: dict[str, str]

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def _get_param_names(self) -> list[str]: ...
    def _find_param(self, name: str) -> NvParam | None: ...
    def _add_param(self, name: str, supported_classes: Any, default: Any, getter: Any, setter: Any, layer: int) -> None: ...
    def get_param_strict(self, name: str) -> NvParam: ...
    def get_param(self, name: str) -> NvParam | None: ...
    def get_param_value(self, name: str) -> Any: ...
    def set_param_value(self, name: str, value: Any) -> None: ...
    def get_nvrect(self) -> NvRect: ...
    def rel(self, vec: NvVector2) -> NvVector2: ...
    def relx(self, num: float) -> float: ...
    def rely(self, num: float) -> float: ...
    def relm(self, num: float) -> float: ...
    def relx_custom(self, num: float, min: float, max: float) -> float: ...
    def rely_custom(self, num: float, min: float, max: float) -> float: ...
    def relm_custom(self, num: float, min: float, max: float) -> float: ...
    def set_coordinates(self, coordinates: NvVector2) -> None: ...
    def _coordinates_setter(self, coordinates: NvVector2) -> bool: ...