[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pygame-nevui"
version = "0.5.0"
authors = [
  { name="GolemNikidastrov", email="bebrovgolem@gmail.com" },
]
description = "A powerful GUI framework for Pygame that allows you to create menus"
readme = "README.md" # Укажи файл с описанием
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pygame-ce>=2.3.0", 
    "numpy",
    "Pillow",
]

[project.urls]
Homepage = "https://github.com/GolemBebrov/pygame-nevui"
Repository = "https://github.com/GolemBebrov/pygame-nevui"