# This file was generated by stubgen-pyx v0.2.22 from src/nevu_ui/fast/nvspecific/nvspec.pyx

from typing import Any, TypedDict

from _typeshed import Incomplete

from nevu_ui.fast.nevucobj.nevucobj import NevuCobject


class PyListObject(TypedDict):
    ob_item: Incomplete

def scrollable_update_collided(collided_items: list[Any]): ...
def scrollable_recollide_items(self: NevuCobject, items: list[Any]): ...
def _manager_main_loop_opt(self) -> None: ...
def _manager_main_loop_main(self) -> None: ...
