def scrollable_update_collided(collided_items: list) -> None: ...
def scrollable_recollide_items(self, items: list) -> None: ...
def menu_draw_raylib(self, bg) -> None: ...
def menu_draw_sdl(self, bg) -> None: ...
def menu_draw_pygame(self, bg) -> None: ...