from .components.nevuobj import NevuObject
from .components.nevuobj.typehints import nevu_object_globals
from .components.widgets import (
    Button,
    Element,
    ElementSwitcher,
    EmptyWidget,
    Gif,
    Image,
    Input,
    Label,
    MusicPlayer,
    ProgressBar,
    RectCheckBox,
    Slider,
    Switch,
    Widget,
)
from .components.layouts import (
    CheckBoxGroup,
    ColorPicker,
    Column,
    Gallery_Pages,
    Grid,
    LayoutType,
    Pages,
    Panel,
    Row,
    ScrollableColumn,
    ScrollableRow,
    StackColumn,
    StackRow,
)
from . import components, core, presentation, utils
from .components.widgets.typehints import widget_globals
from .core import size
from .core.annotations import VERSION, Annotations
from .core.classes import BorderConfig, TooltipType, nevu_globals
from .core.enums import (
    Align,
    AnimationType,
    Backend,
    CacheType,
    ConfigLoadType,
    EventType,
    GradientType,
    HoverState,
    LinearSide,
    RadialPosition,
)
from .core.size.units import (
    Fill,
    FillH,
    FillW,
    Gc,
    Gch,
    Gcw,
    PercentSizeRule,
    Px,
    SizeRule,
    SizeUnit,
    Vh,
    Vw,
    cfill,
    cfillh,
    cfillw,
    cgc,
    cgch,
    cgcw,
    cvh,
    cvw,
    fill,
    fill_all,
    fill_half,
    fill_perc,
    fillh,
    fillw,
    gc,
    gch,
    gcw,
    px,
    vh,
    vw,
)
from .core.state import nevu_state
from .fast import NvVector2
from .fast.nevucache.nevucache import Cache
from .fast.nvrect import NvRect
from .fast.nvrendertex import NvRenderTexture
from .manager import Manager
from .menu import Menu
from .overlay import Tooltip, overlay
from .parser import (
    apply_config,
    get_all_colors,
    get_all_colorthemes,
    get_all_styles,
    get_color,
    get_colortheme,
    get_style,
)
from .presentation import animations
from .presentation.color import (
    Color,
    ColorPair,
    ColorSubTheme,
    ColorTheme,
    ColorThemeLibrary,
    PairColorRole,
    SubThemeRole,
    TupleColorRole,
)
from .presentation.style import StateVariable, Style, default_style
from .rendering import Gradient
from .utils import InputType, Keys, NevuEvent, Time, keyboard, load_font, mouse, time
from .window.window import (
    ConfiguredWindow,
    InitializedWindow,
    ResizeType,
    Window,
    ZRequest,
)

__all__ = [
    # ===Most Used===
    "Menu",
    "Window",
    "ConfiguredWindow",
    "NevuObject",
    "Manager",
    "NvVector2",
    "nevu_state",
    "apply_config",
    "get_style",
    "get_color",
    "get_all_styles",
    "get_all_colors",
    "overlay",
    "TooltipType",
    # ===Widgets===
    "Widget",
    "Label",
    "Button",
    "EmptyWidget",
    "RectCheckBox",
    "Image",
    "Gif",
    "Input",
    "MusicPlayer",
    "ElementSwitcher",
    "Element",
    "ProgressBar",
    "Slider",
    "Tooltip",
    "Switch",
    # ===Layouts===
    "LayoutType",
    "Grid",
    "Row",
    "Column",
    "ScrollableColumn",
    "ScrollableRow",
    "ColorPicker",
    "Pages",
    "Gallery_Pages",
    "StackRow",
    "StackColumn",
    "CheckBoxGroup",
    "Panel",
    # ===Utils===
    "time",
    "Time",
    "mouse",
    "keyboard",
    "Cache",
    "NevuEvent",
    "InputType",
    "NvRect",
    "load_font",
    "load_image",
    "load_image_texture",
    "gradient_queue",
    "Keys",
    "NvRenderTexture",
    # ===Size vars===
    "Fill",
    "FillW",
    "FillH",
    "Vh",
    "Vw",
    "Gc",
    "Gcw",
    "Gch",
    "fill",
    "fillw",
    "fillh",
    "vh",
    "vw",
    "gc",
    "gcw",
    "gch",
    "px",
    "Px",
    "cfill",
    "cfillw",
    "cfillh",
    "cvh",
    "cvw",
    "cgc",
    "cgcw",
    "cgch",
    # ===Color===
    "Color",
    "ColorTheme",
    "ColorSubTheme",
    "ColorPair",
    "ColorThemeLibrary",
    "SubThemeRole",
    "PairColorRole",
    "TupleColorRole",
    # ===Style===
    "Style",
    "default_style",
    "StateVariable",
    "Gradient",
    "ConfigLoadType",
    # ===Enums===
    "Align",
    "LinearSide",
    "RadialPosition",
    "GradientType",
    "EventType",
    "ResizeType",
    "Backend",
    "AnimationType",
    # ===Submodules===
    "animations",
    "utils",
    "size",
    "core",
    "presentation",
    "fast",
    "rendering",
    "components",
]

# okabe 1.048596% based, lelush buryatskiy povelevae bagi uydite
print(f"nevu-ui {VERSION}")
