# This file was generated by stubgen-pyx v0.2.16 from fast/zsystem/fast_zsystem.pyx

from nevu_ui.fast.nvvector2.nvvector2 import NvVector2


class ZRequest:
    on_hover_func: object
    on_unhover_func: object
    on_click_func: object
    on_scroll_func: object
    on_keyup_func: object
    on_keyup_abandon_func: object

    def __init__(self, link, on_hover_func=None, on_unhover_func=None, on_click_func=None, on_keyup_func=None, on_keyup_abandon_func=None, on_scroll_func=None): ...

class ZSystem:
    last_hovered_request: object
    clicked_request: object
    live_requests: list
    is_dirty: bool

    def __init__(self): ...
    def add(self, z_request: ZRequest) -> None: ...
    def mark_dirty(self): ...
    def get_active_requests(self) -> list: ...
    def cycle(self, mouse_pos: NvVector2, mouse_down: bool, mouse_up: bool, any_wheel: bool, wheel_down: bool): ...
