from typing import TYPE_CHECKING, Any
from nevu_ui.core import Annotations
from nevu_ui.presentation.color import Color
from nevu_ui.fast.nvrect.nvrect import NvRect
from nevu_ui.fast.nvvector2.nvvector2 import NvVector2

if TYPE_CHECKING:
    from pyray import Texture

class WindowRendererBase: 
    root: Any
    
    # === Sizes ===
    def get_tuple_rect(self) -> tuple[int, int, int, int]: ...
    def get_nvrect(self) -> NvRect: ...
    def get_size_tuple(self) -> tuple[int, int]: ...
    def get_size_nvvec(self) -> NvVector2: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...

    # === Misc ===
    def update(self) -> None: ...
    def begin_frame(self) -> None: ...
    def end_frame(self) -> None: ...
    def clear(self, color: Any = ...) -> None: ...
    def set_title(self, title: str) -> None: ...
    def load_image(self, path: str) -> Any: ...
    def blit(self, source: Any, dest: Annotations.dest_like) -> None: ...
    
    @property
    def screen(self) -> Any: ...
    
class WindowRendererSdl(WindowRendererBase):
    window: Any
    renderer: Any
    surface: Any

    @staticmethod
    def create_initialized(window: Any, sdl_window: Any, renderer: Any) -> WindowRendererSdl: ...

    def __init__(self, title: str, size: tuple[int, int], root: Any, **kwargs: Any) -> None: ...

    # === Blit ===
    def blit(self, source: Any, dest: Any) -> None: ...

    # === Misc ===
    def set_target(self, texture: Any) -> None: ...
    def create_target_texture(self, width: int, height: int) -> Any: ...


class WindowRendererRaylib(WindowRendererBase):
    _sdf_locs: dict[str, int]
    _border_locs: dict[str, int]

    @staticmethod
    def create_initialized(window: Any) -> WindowRendererRaylib: ...

    def __init__(self, title: str, size: tuple[int, int], root: Any, **kwargs: Any) -> None: ...
    def load_raylib_fast_bindings(self) -> None: ...

    # === Blit ===
    def blit(self, source: Texture, dest: tuple[int, int] | tuple[int, int, int, int], flip: bool = True, color: Annotations.rgba_color = Color.White, angle: float = 0.0) -> None: ... #type: ignore
    def fast_blit(self, source: Texture, dest: tuple[int, int], color: Annotations.rgba_color = Color.White) -> None: ...
    def fast_blit_pro(self, source: Texture, dest: tuple[int, int] | tuple[int, int, int, int], flip: bool = True, color: Annotations.rgba_color = Color.White) -> None: ...
    def blit_rect_pro(self, source: Texture, dest: tuple[int, int, int, int], flip: bool = True, color: Annotations.rgba_color = Color.White, angle: float = 0.0, source_rect: Annotations.rect_like | None = None, mode: int = 0) -> None: ...
    def blit_rect_vec(self, source: Texture, coordinates: tuple[int, int], flip: bool = True, color: Annotations.rgba_color = Color.White, source_rect: Annotations.rect_like | None = None, mode: int = 0) -> None: ...
    
    def blit_sdf(self, source: Texture, dest: tuple[int, int, int, int], radii: float | tuple[float, float, float, float] | Annotations.rect_like, flip: bool = True, mode: int = 0) -> None: ...
    def blit_sdf_vec(self, source: Texture, coordinates: tuple[int, int], radii: float | tuple[float, float, float, float] | Annotations.rect_like, flip: bool = True, mode: int = 0) -> None: ...
    def fast_blit_sdf_vec(self, source: Texture, coordinates: tuple[int, int], radii: float | tuple[float, float, float, float] | Annotations.rect_like, flip: bool = True) -> None: ...
    
    def blit_borders(self, source: Texture, dest_rect: tuple[int, int, int, int], radii: tuple[float, float, float, float], border_color: Any, color: Annotations.rgba_color = Color.White, thickness: float = 1, flip: bool = True, mode: int = 0) -> None: ...
    def blit_borders_vec(self, source: Texture, coordinates: tuple[int, int], radii: tuple[float, float, float, float], border_color: Any, color: Annotations.rgba_color = Color.White, thickness: float = 1, flip: bool = True) -> None: ...
    def fast_blit_borders_vec(self, source: Texture, coordinates: tuple[int, int], radii: tuple[float, float, float, float], border_color: Any, thickness: float = 1, flip: bool = True) -> None: ...

    # === Shaders ===
    def _begin_sdf(self, width: float, height: float, radii: tuple) -> None: ...
    def _begin_borders(self, width: float, height: float, radii: tuple, border_color: tuple, thickness: float) -> None: ...

    # === Misc ===
    def load_image(self, path: str) -> Texture: ...

class WindowRendererPygame(WindowRendererBase):
    window: Any
    
    @staticmethod
    def create_initialized(window: Any, screen: Any) -> WindowRendererPygame: ...

    def __init__(self, title: str, size: tuple[int, int], root: Any, flags: int = 0, **kwargs: Any) -> None: ...

    # === Misc ===
    def flip(self) -> None: ...
    def blit(self, source: Any, dest: Annotations.dest_like) -> None: ...