import nevu_ui.core.modules as md
from typing import TYPE_CHECKING, Any, overload
from nevu_ui.core import Annotations
from nevu_ui.presentation.color import Color
from nevu_ui.fast.nvrect import NvRect

if TYPE_CHECKING:
    from pyray import Texture

class DisplayBase:
    root: Any
    def __init__(self, root: Any) -> None: ...
    def begin_frame(self) -> None: ...
    def get_rect(self) -> NvRect: ...
    def get_size(self) -> tuple[int, int]: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def blit(self, source: Any, dest: Any) -> None: ...
    def clear(self, color: Annotations.rgba_color = (0, 0, 0, 0)) -> None: ...
    def fill(self, color: Annotations.rgba_color) -> None: ...
    def update(self) -> None: ...
    def load_image(self, path: str) -> Any: ...
    def end_frame(self) -> None: ...

class DisplaySdl(DisplayBase):
    window: Any
    renderer: Any
    surface: Any
    def __init__(self, title: str, size: Annotations.dest_like, root: Any, **kwargs: Any) -> None: ...
    def get_rect(self) -> NvRect: ...
    def get_size(self) -> tuple[int, int]: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def set_target(self, texture: Any) -> None: ...
    def update(self) -> None: ...
    def end_frame(self) -> None: ...
    def blit(self, source: Any, dest_rect: Any) -> None: ...
    def clear(self, color: Any | None = None) -> None: ...
    def create_texture_target(self, width: int, height: int) -> Any: ...
    def load_image(self, path: str) -> Any: ...

class DisplayRayLib(DisplayBase):
    def __init__(self, title: str, size: Annotations.dest_like, root: Any, **kwargs: Any) -> None: ...
    def load_raylib_fast_bindings(self) -> None: ...
    def blit(self, source: Texture, dest: Annotations.rect_like, flip: bool = True, color: Annotations.rgba_color = Color.White, angle: int | float = 0.0) -> None: ...
    def fast_blit(self, source: Texture, dest: Annotations.dest_like, color: Annotations.rgba_color = Color.White) -> None: ...
    def fast_blit_pro(self, source: Texture, dest: Annotations.dest_like, flip: bool = True, color: Annotations.rgba_color = Color.White) -> None: ...
    def blit_rect_pro(self, source: Texture, dest: Annotations.rect_like, flip: bool = True, color: Annotations.rgba_color = Color.White, angle: int | float | None = None, source_rect: Annotations.rect_like | None = None, mode: Any | None = None) -> None: ...
    def blit_rect_vec(self, source: Texture, coordinates: Annotations.dest_like, flip: bool = True, color: Annotations.rgba_color = Color.White, source_rect: Annotations.rect_like | None = None, mode: Any | None = None) -> None: ...
    def blit_sdf(self, source: Texture, dest: Annotations.rect_like, radii: Annotations.rect_like, flip: bool = True, mode: Any | None = None) -> None: ...
    def blit_sdf_vec(self, source: Texture, coordinates: Annotations.dest_like, radii: Annotations.rect_like, flip: bool = True, mode: Any | None = None) -> None: ...
    def fast_blit_sdf_vec(self, source: Texture, coordinates: Annotations.dest_like, radii: Annotations.rect_like, flip: bool = True) -> None: ...
    def blit_borders(self, source: Texture, dest_rect: Annotations.rect_like, radii: Annotations.rect_like, border_color: Annotations.rgb_like_color, color: Annotations.rgb_like_color = Color.White, thickness: float = 1, flip: bool = True, mode: Any | None = None) -> None: ...
    def blit_borders_vec(self, source: Texture, coordinates: Annotations.dest_like, radii: Annotations.rect_like, border_color: Annotations.rgb_like_color, color: Annotations.rgb_like_color = Color.White, thickness: float = 1, flip: bool = True) -> None: ...
    def fast_blit_borders_vec(self, source: Texture, coordinates: Annotations.dest_like, radii: Annotations.rect_like, border_color: Annotations.rgb_like_color, thickness: float = 1, flip: bool = True) -> None: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def get_rect(self) -> NvRect: ...
    def get_size(self) -> tuple[int, int]: ...
    def clear(self, color: Annotations.rgb_like_color = (0, 0, 0)) -> None: ...
    def begin_frame(self) -> None: ...
    def update(self) -> None: ...
    def end_frame(self) -> None: ...
    def load_image(self, path: str) -> Texture: ...

class DisplayClassic(DisplayBase):
    window: Any
    def __init__(self, title: str, size: Annotations.dest_like, root: Any, flags: int = 0, **kwargs: Any) -> None: ...
    def get_rect(self) -> Any: ...
    def get_size(self) -> tuple[int, int]: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def clear(self, color: Annotations.rgb_like_color = (0, 0, 0)) -> None: ...
    def update(self) -> None: ...
    def flip(self) -> None: ...
    def blit(self, source: Any, dest: Annotations.dest_like) -> None: ...
    def load_image(self, path: str) -> Any: ...