from nevu_ui.fast.nvrendertex import NvRenderTexture
from nevu_ui.fast.nvvector2 import NvVector2
from nevu_ui.core import GradientType

class GradientRaylib():
    def __init__(self, colors, type: GradientType = GradientType.Linear, direction=None, angle=None, center=None, transparency=None): ...
    @staticmethod
    def from_pygame(pygame_gradient): ...
    @classmethod
    def _ensure_resources(cls): ...

    def generate_texture(self, width: int, height: int) -> "NvRenderTexture": ...

class ClickGradient(GradientRaylib):
    def __init__(self, colors, type: GradientType = GradientType.Radial, direction=None, angle=None, center=None, transparency=None): ...
    def set_center_nvvec(self, center: NvVector2): ...
    def set_weight(self, index: int, weight: float): ...
    def set_center(self, center: tuple): ...
    def _recalculate_stops(self): ...
    def draw(self, x: float, y: float, width: float, height: float): ...